apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello
  description: Phase 2 smoke deployment - StatelessServiceWithBucket
  annotations:
    backstage.io/source-location: url:https://github.com/{{ ORG_GH }}/fleet-gitops/blob/main/projects/smoke-team/deployments/hello.yaml
    backstage.io/kubernetes-id: hello
  labels:
    fleet.platform/kro-instance: hello
spec:
  type: service
  lifecycle: production
  owner: group:default/smoke-team
  system: system:default/smoke-team
