apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.name }} - StatelessServiceWithBucket (scaffolded by Fleet Backstage)
  annotations:
    backstage.io/source-location: url:https://github.com/patel0ankur/fleet-gitops/blob/main/projects/${{ values.project }}/deployments/${{ values.name }}.yaml
  labels:
    fleet.platform/kro-instance: ${{ values.name }}
spec:
  type: service
  lifecycle: production
  owner: ${{ values.project }}
  system: ${{ values.project }}
